### ISSUE TITLE
Can OSC support bluetooth?

### ISSUE THREAD

**Issue by fchen09** [orchetect/OSCKit#23]
Thank you for developing such a useful tool. I am wondering if the OSCKit can support Bluetooth communication besides wifi.

**Comment by orchetect** [comment]
Thank you!

The short answer is yes. OSC is a data encoding format and not a protocol, and OSC 1.1 proposal mentions that it can be used over a variety of transports (USB, Bluetooth, etc.). However the implementation would be up to the software developer.

OSCKit does not provide classes that handle Bluetooth communication since there is no one way to do it. But you could import OSCKitCore (which is just the data encoding portion of the library without the UDP network code) and use `OSCMessage`'s raw data to transmit over a Bluetooth connection that you've set up.

**Comment by fchen09** [comment]
Thanks for the quick reply! I will try it.
